### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by alexandremahdhaoui** [aojea/nat64#3]
Hi aojea, your project looks fantastic and I wanted to try it out. Unfortunately, the go process panics. I tried to check what's causing this err in the `main.go` but wasn't successful.

I was wondering if you had an intuition about the root cause of the issue. I would also be happy to help debug the issue and provide a fix, and could really appreciate some pointers.

### Some information

- CNI: cilium
- Logs:
    ```
    2024/09/05 08:54:55 detected enp0s_as default gateway interface
    2024/09/05 08:54:55 create NAT64 interface nat64 with networks 169.254.64.0/24 and 64:ff9b::/96
    2024/09/05 08:54:55 starting metrics server listening in 0.0.0.0:8881
    panic: runtime error: index out of range [0] with length 0
    
    goroutine 1 [running]:
    main.sync(0xc0001a2030, 0xc0001a20f0)
            /go/src/app/main.go:209 +0xfc9
    main.main()
            /go/src/app/main.go:129 +0xb9a
    ```
- The nat64 iface is created successfully:
    ```
    26: nat64: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
        link/ether de:af:f3:19:ea:0c brd ff:ff:ff:ff:ff:ff
    ```

**Comment by aojea** [comment]
@alexandremahdhaoui what version are you using? it says it panics in

https://github.com/aojea/nat64/blob/b4294e38c330eaed62032a7f62c726ac143a0c0a/main.go#L129


https://github.com/aojea/nat64/blob/b4294e38c330eaed62032a7f62c726ac143a0c0a/main.go#L209

**Comment by aojea** [comment]
hmm @alexandremahdhaoui I think you may have been using an old version, I've updated the docker image, can you try aagain?

**Comment by alexandremahdhaoui** [comment]
Thank you for the quick reply. It seems to work perfectly. I'll run some tests later today and will let you know if something comes up.

Closing this issue for now.
